curl "http://localhost:8983/solr/admin/collections?action=DELETE&name=corpora"
curl "http://localhost:8983/solr/admin/collections?action=DELETE&name=cordis-documents"
curl "http://localhost:8983/solr/admin/collections?action=DELETE&name=cordis-doctopics"
curl "http://localhost:8983/solr/admin/collections?action=DELETE&name=cordis-topicdocs"
curl "http://localhost:8983/solr/admin/collections?action=DELETE&name=cordis-similarities"
curl "http://localhost:8983/solr/admin/configs?action=DELETE&name=corpora"
curl "http://localhost:8983/solr/admin/configs?action=DELETE&name=cordis-documents"
curl "http://localhost:8983/solr/admin/configs?action=DELETE&name=cordis-doctopics"
curl "http://localhost:8983/solr/admin/configs?action=DELETE&name=cordis-topicdocs"
curl "http://localhost:8983/solr/admin/configs?action=DELETE&name=cordis-similarities"
#curl "http://localhost:8983/solr/admin/collections?action=DELETE&name=wikipedia-documents"
#curl "http://localhost:8983/solr/admin/collections?action=DELETE&name=wikipedia-doctopics"
#curl "http://localhost:8983/solr/admin/collections?action=DELETE&name=wikipedia-topicdocs"
#curl "http://localhost:8983/solr/admin/collections?action=DELETE&name=wikipedia-similarities"
#curl "http://localhost:8983/solr/admin/configs?action=DELETE&name=wikipedia-documents"
#curl "http://localhost:8983/solr/admin/configs?action=DELETE&name=wikipedia-doctopics"
#curl "http://localhost:8983/solr/admin/configs?action=DELETE&name=wikipedia-topicdocs"
#curl "http://localhost:8983/solr/admin/configs?action=DELETE&name=wikipedia-similarities"
#curl "http://localhost:8983/solr/admin/collections?action=DELETE&name=patents-documents"
#curl "http://localhost:8983/solr/admin/collections?action=DELETE&name=patents-doctopics"
curl "http://localhost:8983/solr/admin/collections?action=DELETE&name=patents-topicdocs"
#curl "http://localhost:8983/solr/admin/collections?action=DELETE&name=patents-similarities"
#curl "http://localhost:8983/solr/admin/configs?action=DELETE&name=patents-documents"
#curl "http://localhost:8983/solr/admin/configs?action=DELETE&name=patents-doctopics"
curl "http://localhost:8983/solr/admin/configs?action=DELETE&name=patents-topicdocs"
#curl "http://localhost:8983/solr/admin/configs?action=DELETE&name=patents-similarities"
rm -rf data/cordis-*
rm -rf data/wikipedia-*
rm -rf data/patents-*